export const requiredColumns = [
  "Gender",
  "Age",
  "Residence time",
  "No. families",
  "Tb in family",
  "Tb in neighbor",
  "Tb contact",
  "Cough >=2 weeks",
  "Cough <2 weeks",
  "Emptysis",
  "Fever",
  "Thoracalgia",
  "Others",
  "Symptomless",
  "Have similar sym before",
  "X-ray checking",
  "Sputum specimen",
  "Tb diagnosed",
  "Clinical record checked",
  "Anti-tb drug time",
  "Patient final type decided",
  "Subserotype type",
  "TB Type",
];

export const fileToManualMapping = {
  Gender: "gender",
  Age: "age",
  "Residence time": "residenceTime",
  "No. families": "noFamilies",
  "Tb in family": "tbInFamily",
  "Tb in neighbor": "tbInNeighbor",
  "Tb contact": "tbContact",
  "Cough >=2 weeks": "coughTwoWeeks",
  "Cough <2 weeks": "coughLessThan2Weeks",
  Emptysis: "emptysis",
  Fever: "fever",
  Thoracalgia: "thoracalgia",
  Others: "others",
  Symptomless: "symptomless",
  "Have similar sym before": "similarSymBefore",
  "X-ray checking": "xrayChecking",
  "Sputum specimen": "sputumSpecimen",
  "Tb diagnosed": "tbDiagnosed",
  "Clinical record checked": "clinicalRecordChecked",
  "Anti-tb drug time": "antiTbDrugTime",
  "Patient final type decided": "patientFinalTypeDecided",
  "Subserotype type": "subserotypeType",
  "TB Type": "tbType",
};
